# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
  - rubocop-elegant
Lint/NumberConversion:
  Enabled: false
Elegant/GoodMethodName:
  AllowedNames:
    - exit_code
    - name_exists?
    - durable_place
    - durable_save
    - durable_load
    - durable_lock
    - durable_unlock
    - durable_find
    - format_value
    - retry_on
    - will_respond_with
Elegant/ClassInModule:
  Exclude:
    - 'lib/**/*'
    - 'test/**/*'
Elegant/NoClassInModule:
  Exclude:
    - 'test/pact_helper.rb'
Style/StaticClass:
  Exclude:
    - 'lib/baza-rb/version.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/baza-rb.rb'
Metrics/BlockLength:
  Exclude:
    - 'lib/baza-rb.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/baza-rb.rb'
    - 'test/**/*'
